title: Charles Taylor
email: charlestaylor95@gmail.com
description: >-
  I'm currently job seeking; feel free to drop me a line at charlestaylor95@gmail.com
baseurl: ""
url: https://charlestaylor7.github.io/
github_username:  CharlesTaylor7
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
